### ISSUE TITLE
Your network goes out of sync all the time.

### ISSUE THREAD

**Issue by jbnl** [lilsiz/novocoin-project#1]
Dear developer, as you are part of an award winning development team and owner of an award winning cryptocurrency - could you please make sure your network stops going out of sync every 2 minutes? That would be great, thanks.

**Comment by lilsiz** [comment]
What OS are you using ?

**Comment by jbnl** [comment]
I ran a pool on Ubuntu 14.04 for a while, worked fine except for the Daemon going out of sync all the time. I see you are updating the github, are you working on a fix?

**Comment by lilsiz** [comment]
Yes I'm working on a Fix
